package test;

import common.Constants;
import functions.SampleFunction;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import utils.BaseFunctions;
import utils.BaseTest;
import utils.BrowserSetUp;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertTrue;

public class TestDriver extends BaseTest {
// Generated by Selenium IDE

        @Test
        public void sampleTest() {
            SampleFunction.loginToBookshelf("yohanvidusha@gmail.com","password");
            assertTrue(SampleFunction.isBookshelfDisplayed(), "bookshelf is not displayed");
        }

        @Test
        public void  adminTest(){

        }
}
